/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-05-18 03:20:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class content_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<!-- Begin Page Content -->\r\n");
      out.write("          <!-- Page Heading -->\r\n");
      out.write("          <div class=\"d-sm-flex align-items-center justify-content-between mb-4\">\r\n");
      out.write("            <h1 class=\"h3 mb-0 text-gray-800\">Dashboard</h1>\r\n");
      out.write("            <a href=\"#\" class=\"d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm\"><i class=\"fas fa-download fa-sm text-white-50\"></i> Generate Report</a>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- Content Row -->\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Earnings (Monthly) Card Example -->\r\n");
      out.write("            <div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("              <div class=\"card border-left-primary shadow h-100 py-2\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                    <div class=\"col mr-2\">\r\n");
      out.write("                      <div class=\"text-xs font-weight-bold text-primary text-uppercase mb-1\">Earnings (Monthly)</div>\r\n");
      out.write("                      <div class=\"h5 mb-0 font-weight-bold text-gray-800\">$40,000</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-auto\">\r\n");
      out.write("                      <i class=\"fas fa-calendar fa-2x text-gray-300\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Earnings (Monthly) Card Example -->\r\n");
      out.write("            <div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("              <div class=\"card border-left-success shadow h-100 py-2\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                    <div class=\"col mr-2\">\r\n");
      out.write("                      <div class=\"text-xs font-weight-bold text-success text-uppercase mb-1\">Earnings (Annual)</div>\r\n");
      out.write("                      <div class=\"h5 mb-0 font-weight-bold text-gray-800\">$215,000</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-auto\">\r\n");
      out.write("                      <i class=\"fas fa-dollar-sign fa-2x text-gray-300\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Earnings (Monthly) Card Example -->\r\n");
      out.write("            <div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("              <div class=\"card border-left-info shadow h-100 py-2\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                    <div class=\"col mr-2\">\r\n");
      out.write("                      <div class=\"text-xs font-weight-bold text-info text-uppercase mb-1\">Tasks</div>\r\n");
      out.write("                      <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                        <div class=\"col-auto\">\r\n");
      out.write("                          <div class=\"h5 mb-0 mr-3 font-weight-bold text-gray-800\">50%</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                          <div class=\"progress progress-sm mr-2\">\r\n");
      out.write("                            <div class=\"progress-bar bg-info\" role=\"progressbar\" style=\"width: 50%\" aria-valuenow=\"50\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-auto\">\r\n");
      out.write("                      <i class=\"fas fa-clipboard-list fa-2x text-gray-300\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Pending Requests Card Example -->\r\n");
      out.write("            <div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("              <div class=\"card border-left-warning shadow h-100 py-2\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                    <div class=\"col mr-2\">\r\n");
      out.write("                      <div class=\"text-xs font-weight-bold text-warning text-uppercase mb-1\">Pending Requests</div>\r\n");
      out.write("                      <div class=\"h5 mb-0 font-weight-bold text-gray-800\">18</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-auto\">\r\n");
      out.write("                      <i class=\"fas fa-comments fa-2x text-gray-300\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- Content Row -->\r\n");
      out.write("\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Area Chart -->\r\n");
      out.write("            <div class=\"col-xl-8 col-lg-7\">\r\n");
      out.write("              <div class=\"card shadow mb-4\">\r\n");
      out.write("                <!-- Card Header - Dropdown -->\r\n");
      out.write("                <div class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\r\n");
      out.write("                  <h6 class=\"m-0 font-weight-bold text-primary\">Earnings Overview</h6>\r\n");
      out.write("                  <div class=\"dropdown no-arrow\">\r\n");
      out.write("                    <a class=\"dropdown-toggle\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                      <i class=\"fas fa-ellipsis-v fa-sm fa-fw text-gray-400\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"dropdown-menu dropdown-menu-right shadow animated--fade-in\" aria-labelledby=\"dropdownMenuLink\">\r\n");
      out.write("                      <div class=\"dropdown-header\">Dropdown Header:</div>\r\n");
      out.write("                      <a class=\"dropdown-item\" href=\"#\">Action</a>\r\n");
      out.write("                      <a class=\"dropdown-item\" href=\"#\">Another action</a>\r\n");
      out.write("                      <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                      <a class=\"dropdown-item\" href=\"#\">Something else here</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Card Body -->\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <div class=\"chart-area\">\r\n");
      out.write("                    <canvas id=\"myAreaChart\"></canvas>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Pie Chart -->\r\n");
      out.write("            <div class=\"col-xl-4 col-lg-5\">\r\n");
      out.write("              <div class=\"card shadow mb-4\">\r\n");
      out.write("                <!-- Card Header - Dropdown -->\r\n");
      out.write("                <div class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\r\n");
      out.write("                  <h6 class=\"m-0 font-weight-bold text-primary\">Revenue Sources</h6>\r\n");
      out.write("                  <div class=\"dropdown no-arrow\">\r\n");
      out.write("                    <a class=\"dropdown-toggle\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                      <i class=\"fas fa-ellipsis-v fa-sm fa-fw text-gray-400\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"dropdown-menu dropdown-menu-right shadow animated--fade-in\" aria-labelledby=\"dropdownMenuLink\">\r\n");
      out.write("                      <div class=\"dropdown-header\">Dropdown Header:</div>\r\n");
      out.write("                      <a class=\"dropdown-item\" href=\"#\">Action</a>\r\n");
      out.write("                      <a class=\"dropdown-item\" href=\"#\">Another action</a>\r\n");
      out.write("                      <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                      <a class=\"dropdown-item\" href=\"#\">Something else here</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Card Body -->\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <div class=\"chart-pie pt-4 pb-2\">\r\n");
      out.write("                    <canvas id=\"myPieChart\"></canvas>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"mt-4 text-center small\">\r\n");
      out.write("                    <span class=\"mr-2\">\r\n");
      out.write("                      <i class=\"fas fa-circle text-primary\"></i> Direct\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span class=\"mr-2\">\r\n");
      out.write("                      <i class=\"fas fa-circle text-success\"></i> Social\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span class=\"mr-2\">\r\n");
      out.write("                      <i class=\"fas fa-circle text-info\"></i> Referral\r\n");
      out.write("                    </span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- Content Row -->\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Content Column -->\r\n");
      out.write("            <div class=\"col-lg-6 mb-4\">\r\n");
      out.write("\r\n");
      out.write("              <!-- Project Card Example -->\r\n");
      out.write("              <div class=\"card shadow mb-4\">\r\n");
      out.write("                <div class=\"card-header py-3\">\r\n");
      out.write("                  <h6 class=\"m-0 font-weight-bold text-primary\">Projects</h6>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <h4 class=\"small font-weight-bold\">Server Migration <span class=\"float-right\">20%</span></h4>\r\n");
      out.write("                  <div class=\"progress mb-4\">\r\n");
      out.write("                    <div class=\"progress-bar bg-danger\" role=\"progressbar\" style=\"width: 20%\" aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <h4 class=\"small font-weight-bold\">Sales Tracking <span class=\"float-right\">40%</span></h4>\r\n");
      out.write("                  <div class=\"progress mb-4\">\r\n");
      out.write("                    <div class=\"progress-bar bg-warning\" role=\"progressbar\" style=\"width: 40%\" aria-valuenow=\"40\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <h4 class=\"small font-weight-bold\">Customer Database <span class=\"float-right\">60%</span></h4>\r\n");
      out.write("                  <div class=\"progress mb-4\">\r\n");
      out.write("                    <div class=\"progress-bar\" role=\"progressbar\" style=\"width: 60%\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <h4 class=\"small font-weight-bold\">Payout Details <span class=\"float-right\">80%</span></h4>\r\n");
      out.write("                  <div class=\"progress mb-4\">\r\n");
      out.write("                    <div class=\"progress-bar bg-info\" role=\"progressbar\" style=\"width: 80%\" aria-valuenow=\"80\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <h4 class=\"small font-weight-bold\">Account Setup <span class=\"float-right\">Complete!</span></h4>\r\n");
      out.write("                  <div class=\"progress\">\r\n");
      out.write("                    <div class=\"progress-bar bg-success\" role=\"progressbar\" style=\"width: 100%\" aria-valuenow=\"100\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <!-- Color System -->\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-6 mb-4\">\r\n");
      out.write("                  <div class=\"card bg-primary text-white shadow\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      Primary\r\n");
      out.write("                      <div class=\"text-white-50 small\">#4e73df</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 mb-4\">\r\n");
      out.write("                  <div class=\"card bg-success text-white shadow\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      Success\r\n");
      out.write("                      <div class=\"text-white-50 small\">#1cc88a</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 mb-4\">\r\n");
      out.write("                  <div class=\"card bg-info text-white shadow\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      Info\r\n");
      out.write("                      <div class=\"text-white-50 small\">#36b9cc</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 mb-4\">\r\n");
      out.write("                  <div class=\"card bg-warning text-white shadow\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      Warning\r\n");
      out.write("                      <div class=\"text-white-50 small\">#f6c23e</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 mb-4\">\r\n");
      out.write("                  <div class=\"card bg-danger text-white shadow\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      Danger\r\n");
      out.write("                      <div class=\"text-white-50 small\">#e74a3b</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 mb-4\">\r\n");
      out.write("                  <div class=\"card bg-secondary text-white shadow\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      Secondary\r\n");
      out.write("                      <div class=\"text-white-50 small\">#858796</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-lg-6 mb-4\">\r\n");
      out.write("\r\n");
      out.write("              <!-- Illustrations -->\r\n");
      out.write("              <div class=\"card shadow mb-4\">\r\n");
      out.write("                <div class=\"card-header py-3\">\r\n");
      out.write("                  <h6 class=\"m-0 font-weight-bold text-primary\">Illustrations</h6>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <div class=\"text-center\">\r\n");
      out.write("                    <img class=\"img-fluid px-3 px-sm-4 mt-3 mb-4\" style=\"width: 25rem;\" src=\"img/undraw_posting_photo.svg\" alt=\"\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <p>Add some quality, svg illustrations to your project courtesy of <a target=\"_blank\" rel=\"nofollow\" href=\"https://undraw.co/\">unDraw</a>, a constantly updated collection of beautiful svg images that you can use completely free and without attribution!</p>\r\n");
      out.write("                  <a target=\"_blank\" rel=\"nofollow\" href=\"https://undraw.co/\">Browse Illustrations on unDraw &rarr;</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <!-- Approach -->\r\n");
      out.write("              <div class=\"card shadow mb-4\">\r\n");
      out.write("                <div class=\"card-header py-3\">\r\n");
      out.write("                  <h6 class=\"m-0 font-weight-bold text-primary\">Development Approach</h6>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <p>SB Admin 2 makes extensive use of Bootstrap 4 utility classes in order to reduce CSS bloat and poor page performance. Custom CSS classes are used to create custom components and custom utility classes.</p>\r\n");
      out.write("                  <p class=\"mb-0\">Before working with this theme, you should become familiar with the Bootstrap framework, especially the utility classes.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.container-fluid -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
