/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-05-19 07:36:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-3.0.0.jar", Long.valueOf(1589767582992L));
    _jspx_dependants.put("jar:file:/C:/springDev/springStudy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WiseSingleLife/WEB-INF/lib/tiles-jsp-3.0.0.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1336131860000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Royal Estate - Free Bootstrap 4 Template by Colorlib</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/aos.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/ionicons.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap-datepicker.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/jquery.timepicker.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/icomoon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <!-- MainCSS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/main.css\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <!-- ================================ NAVBAR ================================ -->\r\n");
      out.write("    ");
      if (_jspx_meth_tiles_005finsertAttribute_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    <!-- END nav -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- ================================ IMAGE SLIDER ================================ -->\r\n");
      out.write("    <section class=\"home-slider owl-carousel\">\r\n");
      out.write("\t  <div class=\"slider-item\" style=\"background-image:url(images/grocery_store_1.jpg);\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h1 class=\"slider_txt1\">슬기로운 자취생활</h1>\r\n");
      out.write("\t\t\t<h5 class=\"slider_txt2\">프로 자취러를 위한 식료품 가격비교 서비스</h5>\r\n");
      out.write("\t\t\t<div class=\"slider_search_area\">\r\n");
      out.write("\t\t\t\t<input class=\"img_slider_search\" type=\"search\" placeholder=\"검색어를 입력하세요.\">\r\n");
      out.write("\t\t\t\t<button class=\"sliderBtn\">검색</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- overlay 대신 bg-img를 이미지 자체를 수정해서 투명도 높은 검은색 레이어 하나 올리자 -->\r\n");
      out.write("      \t<!-- <div class=\"overlay\"></div> -->\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\t  <div class=\"slider-item\" style=\"background-image:url(images/grocery_store_2.jpg);\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h1 class=\"slider_txt1\">슬기로운 자취생활</h1>\r\n");
      out.write("\t\t\t<h5 class=\"slider_txt2\">프로 자취러를 위한 식료품 가격비교 서비스</h5>\r\n");
      out.write("\t\t\t<div class=\"slider_search_area\">\r\n");
      out.write("\t\t\t\t<input class=\"img_slider_search\" type=\"search\" placeholder=\"검색어를 입력하세요.\">\r\n");
      out.write("\t\t\t\t<button class=\"sliderBtn\">검색</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- overlay 대신 bg-img를 이미지 자체를 수정해서 투명도 높은 검은색 레이어 하나 올리자 -->\r\n");
      out.write("      \t<!-- <div class=\"overlay\"></div> -->\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!-- ================================== PROMOTION VER2 ================================== -->\t\r\n");
      out.write("<section class=\"ftco-section\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t<div class=\"row justify-content-center mb-5 pb-3\">\r\n");
      out.write("\t\t<div class=\"col-md-7 heading-section text-center ftco-animate\">\r\n");
      out.write("\t\t\t<span class=\"subheading\">슬기로운 자취생활을 위한</span>\r\n");
      out.write("\t\t  <h2 class=\"mb-4\">마트별 할인소식</h2>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row d-flex\">\r\n");
      out.write("\t  <div class=\"col-md-3 d-flex ftco-animate\">\r\n");
      out.write("\t\t<div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("\t\t  <a href=\"http://emart.ssg.com/planshop/detail.ssg?dispCmptId=6000355090\" target=\"_blank\" class=\"block-20\" style=\"background-image: url('images/emart1.jpg');\">\r\n");
      out.write("\t\t  </a>\r\n");
      out.write("\t\t  <div class=\"text mt-3 d-block\">\r\n");
      out.write("\t\t\t<h3 class=\"heading mt-3\">\r\n");
      out.write("\t\t\t\t<a href=\"#\">[이마트] 이번 주 이마트 전단 광고</a>\r\n");
      out.write("\t\t\t</h3>\r\n");
      out.write("\t\t\t<!-- <div class=\"meta mb-3\">\r\n");
      out.write("\t\t\t  <div><a href=\"#\">Dec 6, 2018</a></div>\r\n");
      out.write("\t\t\t  <div><a href=\"#\">Admin</a></div>\r\n");
      out.write("\t\t\t  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\r\n");
      out.write("\t\t\t</div> -->\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"col-md-3 d-flex ftco-animate\">\r\n");
      out.write("\t\t<div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("\t\t  <a href=\"http://emart.ssg.com/event/eventDetail.ssg?promId=1100526737\" target=\"_blank\" class=\"block-20\" style=\"background-image: url('images/emart2.jpg');\">\r\n");
      out.write("\t\t  </a>\r\n");
      out.write("\t\t  <div class=\"text mt-3\">\r\n");
      out.write("\t\t\t<h3 class=\"heading mt-3\">\r\n");
      out.write("\t\t\t\t<a href=\"#\">[이마트] 홈핑&홈크닉은 Emartmall life</a>\r\n");
      out.write("\t\t\t</h3>\r\n");
      out.write("\t\t\t<!-- <div class=\"meta mb-3\">\r\n");
      out.write("\t\t\t  <div><a href=\"#\">Dec 6, 2018</a></div>\r\n");
      out.write("\t\t\t  <div><a href=\"#\">Admin</a></div>\r\n");
      out.write("\t\t\t  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\r\n");
      out.write("\t\t\t</div> -->\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"col-md-3 d-flex ftco-animate\">\r\n");
      out.write("\t\t<div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("\t\t  <a href=\"http://www.homeplus.co.kr/app.exhibition.eplacard.Eplacard.ghs?comm=usr.eplacard.inf&WT.ac=Main_GNB_leaflet\" target=\"_blank\" class=\"block-20\" style=\"background-image: url('images/homeplus1.jpg');\">\r\n");
      out.write("\t\t  </a>\r\n");
      out.write("\t\t  <div class=\"text mt-3\">\r\n");
      out.write("\t\t\t<h3 class=\"heading mt-3\"><a href=\"#\">[홈플러스] 이번 주 홈플러스 전단</a></h3>\r\n");
      out.write("\t\t\t<!-- <div class=\"meta mb-3\">\r\n");
      out.write("\t\t\t  <div><a href=\"#\">Dec 6, 2018</a></div>\r\n");
      out.write("\t\t\t  <div><a href=\"#\">Admin</a></div>\r\n");
      out.write("\t\t\t  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\r\n");
      out.write("\t\t\t</div> -->\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"col-md-3 d-flex ftco-animate\">\r\n");
      out.write("\t\t<div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("\t\t  <a href=\"blog-single.html\" class=\"block-20\" style=\"background-image: url('images/homeplus2.jpg');\">\r\n");
      out.write("\t\t  </a>\r\n");
      out.write("\t\t  <div class=\"text mt-3\">\r\n");
      out.write("\t\t\t<h3 class=\"heading mt-3\"><a href=\"#\">Even the all-powerful Pointing has no control about the blind texts</a></h3>\r\n");
      out.write("\t\t\t<!-- <div class=\"meta mb-3\">\r\n");
      out.write("\t\t\t  <div><a href=\"#\">Dec 6, 2018</a></div>\r\n");
      out.write("\t\t\t  <div><a href=\"#\">Admin</a></div>\r\n");
      out.write("\t\t\t  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\r\n");
      out.write("\t\t\t</div> -->\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"col-md-3 d-flex ftco-animate\">\r\n");
      out.write("\t\t<div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("\t\t  <a href=\"blog-single.html\" class=\"block-20\" style=\"background-image: url('images/lottemart1.jpg');\">\r\n");
      out.write("\t\t  </a>\r\n");
      out.write("\t\t  <div class=\"text mt-3 d-block\">\r\n");
      out.write("\t\t\t<h3 class=\"heading mt-3\"><a href=\"#\">Even the all-powerful Pointing has no control about the blind texts</a></h3>\r\n");
      out.write("\t\t\t<!-- <div class=\"meta mb-3\">\r\n");
      out.write("\t\t\t  <div><a href=\"#\">Dec 6, 2018</a></div>\r\n");
      out.write("\t\t\t  <div><a href=\"#\">Admin</a></div>\r\n");
      out.write("\t\t\t  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\r\n");
      out.write("\t\t\t</div> -->\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"col-md-3 d-flex ftco-animate\">\r\n");
      out.write("\t\t<div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("\t\t  <a href=\"blog-single.html\" class=\"block-20\" style=\"background-image: url('images/lottemart2.jpg');\">\r\n");
      out.write("\t\t  </a>\r\n");
      out.write("\t\t  <div class=\"text mt-3\">\r\n");
      out.write("\t\t\t<h3 class=\"heading mt-3\"><a href=\"#\">Even the all-powerful Pointing has no control about the blind texts</a></h3>\r\n");
      out.write("\t\t\t<!-- <div class=\"meta mb-3\">\r\n");
      out.write("\t\t\t  <div><a href=\"#\">Dec 6, 2018</a></div>\r\n");
      out.write("\t\t\t  <div><a href=\"#\">Admin</a></div>\r\n");
      out.write("\t\t\t  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\r\n");
      out.write("\t\t\t</div> -->\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"col-md-3 d-flex ftco-animate\">\r\n");
      out.write("\t\t<div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("\t\t  <a href=\"blog-single.html\" class=\"block-20\" style=\"background-image: url('images/image_7.jpg');\">\r\n");
      out.write("\t\t  </a>\r\n");
      out.write("\t\t  <div class=\"text mt-3\">\r\n");
      out.write("\t\t\t<h3 class=\"heading mt-3\"><a href=\"#\">Even the all-powerful Pointing has no control about the blind texts</a></h3>\r\n");
      out.write("\t\t\t<!-- <div class=\"meta mb-3\">\r\n");
      out.write("\t\t\t  <div><a href=\"#\">Dec 6, 2018</a></div>\r\n");
      out.write("\t\t\t  <div><a href=\"#\">Admin</a></div>\r\n");
      out.write("\t\t\t  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\r\n");
      out.write("\t\t\t</div> -->\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"col-md-3 d-flex ftco-animate\">\r\n");
      out.write("\t\t<div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("\t\t  <a href=\"blog-single.html\" class=\"block-20\" style=\"background-image: url('images/image_8.jpg');\">\r\n");
      out.write("\t\t  </a>\r\n");
      out.write("\t\t  <div class=\"text mt-3\">\r\n");
      out.write("\t\t\t<h3 class=\"heading mt-3\"><a href=\"#\">Even the all-powerful Pointing has no control about the blind texts</a></h3>\r\n");
      out.write("\t\t\t<!-- <div class=\"meta mb-3\">\r\n");
      out.write("\t\t\t  <div><a href=\"#\">Dec 6, 2018</a></div>\r\n");
      out.write("\t\t\t  <div><a href=\"#\">Admin</a></div>\r\n");
      out.write("\t\t\t  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\r\n");
      out.write("\t\t\t</div> -->\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</section>\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<!-- ================================== FOOTER ================================== -->\r\n");
      out.write("    ");
      if (_jspx_meth_tiles_005finsertAttribute_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <!-- loader -->\r\n");
      out.write("  <div id=\"ftco-loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\"/><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"/></svg></div>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("  <script src=\"js/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.stellar.min.js\"></script>\r\n");
      out.write("  <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("  <script src=\"js/aos.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("  <script src=\"js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.timepicker.min.js\"></script>\r\n");
      out.write("  <script src=\"js/scrollax.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false\"></script>\r\n");
      out.write("  <script src=\"js/google-map.js\"></script>\r\n");
      out.write("  <script src=\"js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f0 = new org.apache.tiles.jsp.taglib.InsertAttributeTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tiles_005finsertAttribute_005f0);
    try {
      _jspx_th_tiles_005finsertAttribute_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/main/main.jsp(28,4) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f0.setName("nav");
      _jspx_th_tiles_005finsertAttribute_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tiles_005finsertAttribute_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f1 = new org.apache.tiles.jsp.taglib.InsertAttributeTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tiles_005finsertAttribute_005f1);
    try {
      _jspx_th_tiles_005finsertAttribute_005f1.setJspContext(_jspx_page_context);
      // /WEB-INF/main/main.jsp(195,4) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f1.setName("footer");
      _jspx_th_tiles_005finsertAttribute_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tiles_005finsertAttribute_005f1);
    }
    return false;
  }
}
